### ISSUE TITLE
Can't get access token from sandbox

### ISSUE THREAD

**Issue by kavandersluis** [virencehealth/apiserver.virencehealth.com#93]
Hi,

I am a new user to the sandbox.  I am following the setup guide at https://mydata.gehealthcare.com/access-centricity-apis.  I've set up my application in the Dev Center, and am signing into a Personal Account (not work account).  I get thru the login sequence, and get back an auth code.  When I attempt to get the access token using that auth code, I get the following error message:

{
    "expires_in": 0,
    "error": "invalid_client",
    "error_description": "An unexpected error has occurred. Please try this operation again later."
}

To get the access token, I'm using the endpoint https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/token

I'm following the example for the setup, i.e. using basic auth with my app credentials, passing the redirect URL an auth code, etc.

Can anybody shed light on why I'm getting this error, or recommend how to further diagnose the problem?

Thanks,
Kirstan

**Comment by Torin-Shepard-athena** [comment]
System was restarted Dec 16, 2019. Work account authorization flow should be working again.

**Comment by kavandersluis** [comment]
Thanks for the note, Torin. I am actually trying to get the Patient workflow (Personal Account) to work.  For the Work account flow that you mention, I am able to get to work just fine.

The patient workflow is still failing.  Now the username/password is not working.  For the Personal Account, the username/password should be Walter.caldwell@outlook.com/TestPatient!@.  I'm not even able to get an auth code now.  I think perhaps the password is not longer correct (perhaps somebody reset it?)

Thanks,

Kirstan

**Comment by KedarGanta** [comment]
@kavandersluis  It looks like there is an issue with the account. We reset the password. Please use this  Walter.caldwell@outlook.com/TestPatient!@!      @Torin-Shepard-athena

**Comment by ychowdhary** [comment]
Please reopen if you still encounter this issue.
